from __future__ import annotations

import argparse
import json
import os
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
STATE_REPORT_DIR = ROOT / ".codex" / "state" / "mesh_env"


def _utc_ts_compact() -> str:
    return datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")


def _write_env_file(path: Path, values: dict[str, str]) -> None:
    lines = ["# generated by tools/mesh_configure_env.py"]
    for key in sorted(values):
        val = values[key]
        lines.append(f'export {key}="{val}"')
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _path_status(path: Path) -> dict[str, object]:
    parent = path.parent
    return {
        "path": str(path),
        "exists": path.exists(),
        "parent_exists": parent.exists(),
        "parent_writable": os.access(parent, os.W_OK),
    }


def configure_instance(instance_root: Path, shared_state_root: Path | None) -> dict[str, object]:
    instance_root = instance_root.resolve()
    state_root = (shared_state_root.resolve() if shared_state_root is not None else (instance_root / ".codex" / "state" / "mesh_shared"))

    events_dir = state_root / "events"
    checkpoints_dir = state_root / "checkpoints"
    snapshots_dir = state_root / "snapshots"
    transport_dir = state_root / "transport"
    bridge_dir = state_root / "bridge"
    sandboxes_root = state_root / "mcp_qso_edu" / "sandboxes"

    event_path = events_dir / "events.jsonl"
    checkpoint_path = checkpoints_dir / "checkpoints.json"
    snapshot_root = snapshots_dir
    audit_path = transport_dir / "network_audit.jsonl"
    transport_state_path = transport_dir / "transport_state.json"
    plus_bridge_path = bridge_dir / "plus_bridge.jsonl"

    for path in (events_dir, checkpoints_dir, snapshots_dir, transport_dir, bridge_dir, sandboxes_root):
        path.mkdir(parents=True, exist_ok=True)

    for path in (event_path, checkpoint_path, audit_path, transport_state_path, plus_bridge_path):
        path.touch(exist_ok=True)

    env_values = {
        "QSO_MESH_MODE": "1",
        "QSO_EVENT_STORE_PATH": str(event_path),
        "QSO_CHECKPOINT_STORE_PATH": str(checkpoint_path),
        "QSO_SNAPSHOT_STORE_DIR": str(snapshot_root),
        "QSO_NETWORK_AUDIT_PATH": str(audit_path),
        "QSO_TRANSPORT_STATE_PATH": str(transport_state_path),
        "QSO_PLUS_BRIDGE_PATH": str(plus_bridge_path),
        "QSO_SANDBOX_OP_ROOT": str(sandboxes_root),
    }

    env_file = instance_root / ".codex" / "state" / "mesh.env"
    env_file.parent.mkdir(parents=True, exist_ok=True)
    _write_env_file(env_file, env_values)

    statuses = {
        "event": _path_status(event_path),
        "checkpoint": _path_status(checkpoint_path),
        "audit": _path_status(audit_path),
        "transport_state": _path_status(transport_state_path),
        "plus_bridge": _path_status(plus_bridge_path),
        "snapshot_root": _path_status(snapshot_root),
        "sandbox_root": _path_status(sandboxes_root),
    }
    ok = all(bool(item["parent_writable"]) for item in statuses.values())

    return {
        "instance_root": str(instance_root),
        "env_file": str(env_file),
        "state_root": str(state_root),
        "env": env_values,
        "paths": statuses,
        "ok": ok,
    }


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Configure mesh persistence env paths for one or more instances.")
    parser.add_argument("--instance", action="append", required=True, help="Instance root path (repeatable).")
    parser.add_argument("--shared-state-root", default="", help="Optional absolute shared state root used by all instances.")
    return parser


def main() -> int:
    parser = _parser()
    args = parser.parse_args()
    shared_state_root = Path(args.shared_state_root).resolve() if str(args.shared_state_root).strip() else None
    instances = [Path(item).resolve() for item in args.instance]

    rows = [configure_instance(instance, shared_state_root) for instance in instances]
    STATE_REPORT_DIR.mkdir(parents=True, exist_ok=True)
    run_id = _utc_ts_compact()
    report_path = STATE_REPORT_DIR / f"mesh_env_{run_id}.json"
    report = {
        "run_id": run_id,
        "created_at": datetime.now(timezone.utc).isoformat(),
        "shared_state_root": str(shared_state_root) if shared_state_root is not None else None,
        "instances": rows,
        "ok": all(bool(row.get("ok")) for row in rows),
    }
    report_path.write_text(json.dumps(report, sort_keys=True, indent=2), encoding="utf-8")
    print(str(report_path))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
