#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
STATE_DIR="${ROOT_DIR}/.codex/state"
CERT_DIR="${STATE_DIR}/certs/qso-chat-ws"
ENV_FILE="${STATE_DIR}/qso_chat_ws.env"
CERT_FILE="${CERT_DIR}/server.crt"
KEY_FILE="${CERT_DIR}/server.key"

mkdir -p "${CERT_DIR}"

if [[ ! -f "${CERT_FILE}" || ! -f "${KEY_FILE}" ]]; then
  openssl req \
    -x509 \
    -newkey rsa:4096 \
    -sha256 \
    -days 365 \
    -nodes \
    -keyout "${KEY_FILE}" \
    -out "${CERT_FILE}" \
    -subj "/CN=localhost" >/dev/null 2>&1
fi

auth_token="$(openssl rand -hex 32)"
pq_seed_hex="$(openssl rand -hex 32)"

cat > "${ENV_FILE}" <<EOF
# Generated by tools/setup_qso_chat_ws_hardened.sh
# Local-only development defaults. Do not commit this file.

QSO_CHAT_WS_HOST=0.0.0.0
QSO_CHAT_WS_PORT=9444

QSO_CHAT_WS_TLS_CERT=${CERT_FILE}
QSO_CHAT_WS_TLS_KEY=${KEY_FILE}
QSO_CHAT_WS_AUTH_TOKEN=${auth_token}
QSO_CHAT_WS_PQ_SEED_HEX=${pq_seed_hex}

# Deterministic local anchor mode works with this placeholder contract id.
QSO_CHAT_WS_ANCHOR_CONTRACT_ADDRESS=0x0000000000000000000000000000000000000001
QSO_CHAT_WS_ANCHOR_LIVE=0

# Required for NIST ML-KEM/ML-DSA signer backend.
# Update this path if liboqs is installed elsewhere.
QSO_CHAT_WS_OQS_INSTALL_PATH=/Users/ALISTAIRE/liboqs-build-local

# Fail-closed security gates for submission readiness.
QSO_CHAT_WS_REQUIRE_TLS=1
QSO_CHAT_WS_REQUIRE_AUTH=1
QSO_CHAT_WS_REQUIRE_QUANTUM_ENVELOPE=1
QSO_CHAT_WS_REQUIRE_CONTRACT_ANCHOR=1

# Set these for live on-chain anchoring:
# QSO_CHAT_WS_ANCHOR_RPC_URL=https://your-evm-rpc
# QSO_CHAT_WS_ANCHOR_PRIVATE_KEY=0x...
EOF

chmod 600 "${ENV_FILE}"
chmod 600 "${KEY_FILE}"

echo "Wrote ${ENV_FILE}"
echo "TLS cert: ${CERT_FILE}"
echo "TLS key:  ${KEY_FILE}"
echo "Ready to run: tools/run_qso_chat_ws_hardened.sh"
